image: maven:3.8.5-openjdk-17-slim

services:
  - name: mysql:8.0
    alias: db
    command:
      - --default-authentication-plugin=mysql_native_password

variables:
  MYSQL_ROOT_PASSWORD: root

before_script:
  - apt-get update && apt-get install -y default-mysql-client
  - echo "Waiting for MySQL to be ready..."
  - for i in `seq 1 90`; do
      echo "Trying to connect to MySQL, attempt $i...";
      mysql -h db -uroot -proot -e "SHOW DATABASES;" && break;
      sleep 2;
    done
  - echo "Creating databases..."
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS user_db;"
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS authentication_db;"
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS notification_db;"
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS project_db;"
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS group_db;"
  - mysql -h db -uroot -proot -e "CREATE DATABASE IF NOT EXISTS evaluation_db;"

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test