variables:
  # Configuration for Maven and Java
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

# Define the Docker image for the build environment
image: maven:3-openjdk-17

# Cache dependencies and plugins between builds
cache:
  paths:
    - .m2/repository

# Test stage
test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Build stage
build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean package'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH